module.exports = {
    settings  : [
      { name: 'InterestTerms'},
      { name: 'InternalInvoicesNumSeries'},
      { name: 'Installments'},
      { name: 'ClassificationTypes'},
      { name: 'IssuedGiftVouchers'},
      { name: 'ItemGroupWithholdings'},
      { name: 'Units'},
      { name: 'CustomerCategories'},
      { name: 'ItemClassifications'},
      { name: 'InterestCodes'},
      { name: 'ElectronicInvoicesQueues'},
      { name: 'Bonuses'},
      { name: 'Regions'},
      { name: 'ExtraTaxCustomerDiscounts'},
      { name: 'CrossSalesItems'},
      { name: 'StandardProblems'},
      { name: 'ElectronicRecordStatuses'},
      { name: 'RemainderTexts'},
      { name: 'DefaultItems'},
      { name: 'AlternativeItems'},
      { name: 'PaymentTerms'},
      { name: 'GiftVouchersReceivedNumSeries'},
      { name: 'GiftVouchersNumSeries'},
      { name: 'AgeLimits'},
      { name: 'CreditLimit'},
      { name: 'VatZoneName'},
      { name: 'EnvironmentTax'},
      { name: 'InvoiceMailSettings'}
    ],
    registers : [
      { name:'Accounts'},
      { name:'ItemGroup'},
      { name:'Items'},
      { name:'Contacts'},
      { name:'Receipts'},
      { name:'Invoices'},
      { name:'InternalInvoices'},
      { name:'CurncyCode', disabled:'true'}
    ]
};