module.exports = {
    registers  : [
      //registers:
      { name:'Accounts'},
      { name:'ItemGroups'},
      { name:'Items'},
      { name:'Contacts'},
      { name:'Receipts'},
      { name:'Invoices'},
      { name:'InternalInvoices'},
      { name:'CurncyCodes'},
      { name:'Prices'},
      { name:'Transactions'},
      { name:'Payments'},
      { name:'ExchangeRates'},
      { name:'PriceLists'},
      { name:'OpenInvoices'},
      //settings:
      { name: 'InterestTerms'},
      { name: 'Installments'},
      { name: 'ClassificationTypes'},
      { name: 'IssuedGiftVouchers'},
      { name: 'ItemGroupWithholdings'},
      { name: 'Units'},
      { name: 'CustomerCategories'},
      { name: 'ItemClassifications'},
      { name: 'InterestCodes'},
      { name: 'ElectronicInvoicesQueues'},
      { name: 'Bonuses'},
      { name: 'Regions'},
      { name: 'ExtraTaxCustomerDiscounts'},
      { name: 'CrossSalesItems'},
      { name: 'StandardProblems'},
      { name: 'ElectronicRecordStatuses'},
      { name: 'RemainderTexts'},
      { name: 'DefaultItems'},
      { name: 'AlternativeItems'},
      { name: 'PaymentTerms'}  
    ],
    settings : [
      { name: 'GiftVouchersReceivedNumSeries'},
      { name: 'GiftVouchersNumSeries'},
      { name: 'AgeLimit'},
      { name: 'CreditLimit'},
      { name: 'VatZoneName'},
      { name: 'EnvironmentTax'},
      { name: 'InvoiceMailSetting'},
      { name: 'InternalInvoicesNumSeries'},
      { name: 'BaseCurrency'}
    ]
};